function kq=R(phy,a)
kq=[cos(phy)+a(1)^2*(1-cos(phy)), a(1)*a(2)*(1-cos(phy))-a(3)*sin(phy), a(1)*a(3)*(1-cos(phy))+a(2)*sin(phy);...
   a(1)*a(2)*(1-cos(phy))+a(3)*sin(phy), cos(phy)+a(2)^2*(1-cos(phy)), a(2)*a(3)*(1-cos(phy))-a(1)*sin(phy);...
   a(1)*a(3)*(1-cos(phy))-a(2)*sin(phy), a(2)*a(3)*(1-cos(phy))+a(1)*sin(phy), cos(phy)+a(3)^2*(1-cos(phy))];
end